import Head from "next/head";
import { useCart } from "../feature/cartSlice";
import { useDispatch, useSelector } from "react-redux";
import classNames from "classnames";

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await res.json();
  return {
    props: { posts: data },
  };
}

export default function Home({ posts }) {
  const { myCart, myStock } = useSelector((state) => state);
  const { allProductsQuantity } = myCart;
  const { stockProductsQuantity, isDanger } = myStock;
  const { addToCart } = useCart();
  const dispatch = useDispatch();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <div>
          {posts.map((post) => (
            <div key={post.id} className="title">
              {post.title}
            </div>
          ))}
        </div>
        <div className="container">
          <div className="all__products">
            <h2 className="title">Number Of Product</h2>
            <h3 className="quantity"> {allProductsQuantity} </h3>

            <a href="#" onClick={() => dispatch(addToCart())}>
              Add To Cart
            </a>
          </div>
          <div
            className={classNames("stocks__products", { whenDanger: isDanger })}
          >
            <h2 className="title">Available Products</h2>
            <h3 className="quantity"> {stockProductsQuantity} </h3>
          </div>
        </div>
      </div>
    </div>
  );
}
